# Generated by Django 5.1.6 on 2026-05-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawingimage',
            name='avg_brightness',
        ),
        migrations.RemoveField(
            model_name='drawingimage',
            name='avg_saturation',
        ),
        migrations.RemoveField(
            model_name='drawingimage',
            name='bright_ratio',
        ),
        migrations.RemoveField(
            model_name='drawingimage',
            name='center_density',
        ),
        migrations.RemoveField(
            model_name='drawingimage',
            name='cool_ratio',
        ),
        migrations.RemoveField(
            model_name='drawingimage',
            name='dark_ratio',
        ),
        migrations.RemoveField(
            model_name='drawingimage',
            name='edge_density',
        ),
        migrations.RemoveField(
            model_name='drawingimage',
            name='hue_diversity',
        ),
        migrations.RemoveField(
            model_name='drawingimage',
            name='pastel_ratio',
        ),
        migrations.RemoveField(
            model_name='drawingimage',
            name='spatial_balance',
        ),
        migrations.RemoveField(
            model_name='drawingimage',
            name='warm_ratio',
        ),
    ]
