# Generated by Django 5.1.6 on 2026-05-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_drawingimage_avg_brightness_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawingimage',
            name='color_count',
        ),
        migrations.RemoveField(
            model_name='drawingimage',
            name='dominant_colors',
        ),
        migrations.RemoveField(
            model_name='drawingimage',
            name='stroke_count',
        ),
    ]
